# Generated by Django 2.1.5 on 2019-06-24 19:53

from django.conf import settings
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160412_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Mainimage',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
